# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Artem_Domnikov_20321_HMI_CPD/CPD/Task_3/Task_3_3/product_info.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;Artem_Domnikov_20321_HMI_CPD/CPD/Task_3/Task_3_3/product_info.proto\"c\n\x04\x44\x61ta\x12\x11\n\tdevice_id\x18\x01 \x01(\x05\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x05\x12\x10\n\x08humidity\x18\x03 \x01(\x02\x12\x10\n\x08temp_cel\x18\x04 \x01(\x02\x12\x12\n\nvideo_data\x18\x05 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Artem_Domnikov_20321_HMI_CPD.CPD.Task_3.Task_3_3.data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATA']._serialized_start=63
  _globals['_DATA']._serialized_end=162
# @@protoc_insertion_point(module_scope)
