version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_news
    restart: always
    environment:
      POSTGRES_DB: news-site-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"      

  web:
    build: .
    container_name: next
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres_news:5432/news-site-db
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm start"
  
    
